---
- hosts: all
  become: true
  tasks: 
    - name: template file onto remote hosts
      template:
        src: /home/awstgremoteweb/templates/my_temp.conf.j2
        dest: /home/awstgremoteweb/etc/my_temp.conf
        remote_src: yes
       
        
        
        
        
    

