---
- hosts: all
  become: true
  tasks: 
    - name: template file onto remote hosts
      template:
        src:/home/ec2-user/templates/my_temp.conf.j2
        dest:/home/awstgremoteweb/etc/my_temp.conf
        remote_src: no
        
        
        
        
    

