---
- hosts: all
  become: true
  tasks: 
    - name: template file onto remote hosts
      template:
        src: my_temp.conf.j2
        dest: my_temp.conf
        remote_src: yes
       
        
        
        
        
    

