---
- hosts: all
  vars:
    changeable_variable: "The is some configuration text"
  become: true
  tasks: 
    - name: template file onto remote hosts
      template:
        src: configuration.conf.j2
        dest: /etc/configuration.conf
        remote_src: yes
       
        
        
        
        
    

