---
- hosts: all
  vars:
    changeable_variable: "The is some configuration text"
  become: true
  tasks: 
    - name: template file onto remote hosts
      template:
        src: templates/configuration.conf.j2
        dest: home/awstgremoteweb/configuration.conf
      
       
        
        
        
        
    

